name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.0'
          - '2.7'
          - '2.6'
          - '2.5'
          - '2.4'
          - '2.3'
          - '2.2'
          - '2.1'
          - '2.0'
        gemfile:
          - activerecord_7.0
          - activerecord_6.1
          - activerecord_6.0
          - activerecord_5.2
          - activerecord_5.1
          - activerecord_5.0
          - activerecord_4.2
          - activerecord_4.1
          - activerecord_4.0
        exclude:
          - ruby: '3.0'
            gemfile: activerecord_5.2
          - ruby: '3.0'
            gemfile: activerecord_5.1
          - ruby: '3.0'
            gemfile: activerecord_5.0
          - ruby: '3.0'
            gemfile: activerecord_4.2
          - ruby: '3.0'
            gemfile: activerecord_4.1
          - ruby: '3.0'
            gemfile: activerecord_4.0
          - ruby: '2.7'
            gemfile: activerecord_4.2
          - ruby: '2.7'
            gemfile: activerecord_4.1
          - ruby: '2.7'
            gemfile: activerecord_4.0
          - ruby: '2.6'
            gemfile: activerecord_7.0
          - ruby: '2.6'
            gemfile: activerecord_4.1
          - ruby: '2.6'
            gemfile: activerecord_4.0
          - ruby: '2.5'
            gemfile: activerecord_7.0
          - ruby: '2.5'
            gemfile: activerecord_4.1
          - ruby: '2.5'
            gemfile: activerecord_4.0
          - ruby: '2.4'
            gemfile: activerecord_7.0
          - ruby: '2.4'
            gemfile: activerecord_6.1
          - ruby: '2.4'
            gemfile: activerecord_6.0
          - ruby: '2.4'
            gemfile: activerecord_4.1
          - ruby: '2.4'
            gemfile: activerecord_4.0
          - ruby: '2.3'
            gemfile: activerecord_7.0
          - ruby: '2.3'
            gemfile: activerecord_6.1
          - ruby: '2.3'
            gemfile: activerecord_6.0
          - ruby: '2.2'
            gemfile: activerecord_7.0
          - ruby: '2.2'
            gemfile: activerecord_6.1
          - ruby: '2.2'
            gemfile: activerecord_6.0
          - ruby: '2.1'
            gemfile: activerecord_7.0
          - ruby: '2.1'
            gemfile: activerecord_6.1
          - ruby: '2.1'
            gemfile: activerecord_6.0
          - ruby: '2.1'
            gemfile: activerecord_5.2
          - ruby: '2.1'
            gemfile: activerecord_5.1
          - ruby: '2.1'
            gemfile: activerecord_5.0
          - ruby: '2.0'
            gemfile: activerecord_7.0
          - ruby: '2.0'
            gemfile: activerecord_6.1
          - ruby: '2.0'
            gemfile: activerecord_6.0
          - ruby: '2.0'
            gemfile: activerecord_5.2
          - ruby: '2.0'
            gemfile: activerecord_5.1
          - ruby: '2.0'
            gemfile: activerecord_5.0

    runs-on: ubuntu-20.04
    env:
      RAILS_ENV: test
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run database migrations
        run: bundle exec rake db:migrate

      - name: Run tests
        run: bundle exec rspec

      - name: Run Rubocop
        run: bundle exec rubocop

      - name: Upload coverage data to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
